### ISSUE TITLE
Maquetación componente cronograma

### ISSUE THREAD

**Issue by mario-cartagena** [MAKAIABootcamp/sga-project-front-4#5]
- [x] Elegir el cronograma a trabajar
- [x] Botón de añadir evento
- [x] Botón de editar evento
- [x] Botón para eliminar un evento
- [x] Card para el evento
- [x] Formulario con inputs para nombre y hora del evento
- [x] Botón de cancelar
- [x] Botón de aceptar
- [x] #10

**Comment by AngieMorenoOrtega** [comment]
Estoy trabajando en estilos del cronograma y componente tecnico leer : #10
